apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-health-api
  namespace: flask-health-api
  labels:
    app.kubernetes.io/name: flask-health-api
    app.kubernetes.io/instance: flask-health-api-dev
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: devsecops-platform
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/version: "1.0.0"
    environment: dev
    team: devsecops-platform
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flask-health-api
      app.kubernetes.io/instance: flask-health-api-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flask-health-api
        app.kubernetes.io/instance: flask-health-api-dev
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: flask-health-api
          image: flask-health-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}