apiVersion: v1
kind: Service
metadata:
  name: flask-health-api
  namespace: flask-health-api
  labels:
    apps.kubernetes.io/name: flask-health-api
    apps.kubernetes.io/instance: flask-health-api-dev
    apps.kubernetes.io/component: api
    apps.kubernetes.io/part-of: devsecops-platform
    apps.kubernetes.io/managed-by: kubectl
    environment: dev
    team: devsecops-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: flask-health-api
    apps.kubernetes.io/instance: flask-health-api-dev
  ports:
    - name: http
      port: 5000
      targetPort: http