name: Terraform Validate

on:
  push:
    branches:
      - main
    paths:
      - "labs/terraform/**"
      - ".github/workflows/terraform-validate.yml"

  pull_request:
    branches:
      - main
    paths:
      - "labs/terraform/**"
      - ".github/workflows/terraform-validate.yml"

  workflow_dispatch:

jobs:
  terraform-validate:
    name: Validate Terraform Labs
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        lab:
          - labs/terraform/01-local-file
          - labs/terraform/02-variables-outputs
          - labs/terraform/03-tfvars
          - labs/terraform/04-locals
          - labs/terraform/05-count-foreach
          - labs/terraform/06-maps-objects
          - labs/terraform/07-conditionals
          - labs/terraform/08-modules

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.4

      - name: Terraform fmt check
        working-directory: ${{ matrix.lab }}
        run: terraform fmt -check -recursive

      - name: Terraform init
        working-directory: ${{ matrix.lab }}
        run: terraform init -backend=false

      - name: Terraform validate
        working-directory: ${{ matrix.lab }}
        run: terraform validate